trigger: none

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    UseFederatedAuth: true
    ServiceDirectory: appConfiguRation
    Artifacts:
      - name: azure-Data-Appconfiguration
        groupId: com.azure
        safeName: azureDataAppConfiguration
    TimeoutInMinutes: 90
    SupportedClouds: "Public,UsGov,China"
